export type DuaCategory = "ertalab" | "kechqurun" | "ovqat" | "safar" | "uyqu" | "umumiy";

export interface Dua {
  id: string;
  category: DuaCategory;
  title: string;
  arabic: string;
  uzbek: string;
  transliteration: string;
}

export const DUA_CATEGORIES: { key: DuaCategory; label: string }[] = [
  { key: "umumiy", label: "Umumiy" },
  { key: "ertalab", label: "Ertalab" },
  { key: "kechqurun", label: "Kechqurun" },
  { key: "ovqat", label: "Ovqat" },
  { key: "uyqu", label: "Uyqu" },
  { key: "safar", label: "Safar" },
];

export const DUAS: Dua[] = [
  // ============ UMUMIY (General) ============
  {
    id: "u1",
    category: "umumiy",
    title: "Bismillah",
    arabic: "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ",
    uzbek: "Mehribon va Rahmli Allohning nomi bilan.",
    transliteration: "Bismillahir Rahmanir Rahim",
  },
  {
    id: "u2",
    category: "umumiy",
    title: "Istighfor",
    arabic: "أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لاَ إِلَهَ إِلاَّ هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ",
    uzbek: "Men azim, tirik va barqaror bo'lgan, O'zidan boshqa iloh yo'q Allohdan mag'firat so'rayman va Unga tavba qilaman.",
    transliteration: "Astaghfirullaahal aziiymallazii laa ilaaha illaa huwal hayyul qayyuumu wa atuubu ilayh",
  },
  {
    id: "u3",
    category: "umumiy",
    title: "Quvvat va kuch uchun",
    arabic: "لاَ حَوْلَ وَلاَ قُوَّةَ إِلاَّ بِاللَّهِ",
    uzbek: "Allohdan boshqa kuch va quvvat yo'q.",
    transliteration: "Laa hawla wa laa quwwata illaa billaah",
  },
  {
    id: "u4",
    category: "umumiy",
    title: "Ota-ona uchun dua",
    arabic: "رَبِّ اغْفِرْ لِي وَلِوَالِدَيَّ وَارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
    uzbek: "Parvardigorim! Menga ham, ota-onamga ham mag'firat ayla. Ular meni kichikligimda tarbiya qilganidek, ularga rahm ayla.",
    transliteration: "Rabbighfir lii wa liwaaliidayya warhamhumaa kamaa rabbayaanii saghiiraa",
  },
  {
    id: "u5",
    category: "umumiy",
    title: "Hidoyat uchun",
    arabic: "اللَّهُمَّ اهْدِنَا فِيمَنْ هَدَيْتَ",
    uzbek: "Allohim! Hidoyat berganlaringning qatorida bizga ham hidoyat ber.",
    transliteration: "Allaahummahdinaa fiiman hadayt",
  },
  {
    id: "u6",
    category: "umumiy",
    title: "Yaxshilik uchun",
    arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    uzbek: "Parvardigorimiz! Bizga dunyoda ham, oxiratda ham yaxshilik ber va bizni do'zax azobidan saqlа.",
    transliteration: "Rabbanaa aatinaa fid-dunyaa hasanataw wa fil aakhirati hasanataw wa qinaa azaaban naar",
  },
  {
    id: "u7",
    category: "umumiy",
    title: "Qalbni tuzatish uchun",
    arabic: "يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَى دِينِكَ",
    uzbek: "Ey qalblarni o'zgartiruvchi! Qalbimni Sening dinida mustahkam tut.",
    transliteration: "Yaa muqallibal quluubi sabbit qalbii alaa diinik",
  },
  {
    id: "u8",
    category: "umumiy",
    title: "Ilm va hikmat uchun",
    arabic: "رَبِّ زِدْنِي عِلْمًا",
    uzbek: "Parvardigorim! Ilmimni orttir.",
    transliteration: "Rabbi zidnii ilmaa",
  },
  {
    id: "u9",
    category: "umumiy",
    title: "Tashvishdan xalos bo'lish uchun",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ وَالْعَجْزِ وَالْكَسَلِ",
    uzbek: "Allohim! Dard va qayg'udan, ojizlik va dangasalikdan Sening panohing olayman.",
    transliteration: "Allaahummaa innii a'uuzubika minal hammi wal hazani wal ajzi wal kasal",
  },
  {
    id: "u10",
    category: "umumiy",
    title: "Shukr",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي بِنِعْمَتِهِ تَتِمُّ الصَّالِحَاتُ",
    uzbek: "Uning ne'mati bilan yaxshi ishlar amalga oshgan Allohga hamd bo'lsin.",
    transliteration: "Alhamdulillaahillazii bini'matihi tatimmussaalihaat",
  },
  {
    id: "u11",
    category: "umumiy",
    title: "Musibatda sabr uchun",
    arabic: "إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ",
    uzbek: "Albatta biz Allohnikimiz va albatta biz Unga qaytuvchimiz.",
    transliteration: "Innaa lillaahi wa innaa ilayhi raaji'uun",
  },
  {
    id: "u12",
    category: "umumiy",
    title: "Baraka uchun",
    arabic: "اللَّهُمَّ بَارِكْ لَنَا فِيمَا رَزَقْتَنَا وَقِنَا عَذَابَ النَّارِ",
    uzbek: "Allohim! Bizga bergan rizqingda baraka ber va bizni do'zax azobidan asra.",
    transliteration: "Allaahumma baarik lanaa fiimaa razaqtanaa wa qinaa azaabannaar",
  },
  {
    id: "u13",
    category: "umumiy",
    title: "Hayot va o'lim uchun",
    arabic: "اللَّهُمَّ أَحْيِنِي مَا كَانَتِ الْحَيَاةُ خَيْرًا لِي وَتَوَفَّنِي إِذَا كَانَتِ الْوَفَاةُ خَيْرًا لِي",
    uzbek: "Allohim! Hayot men uchun yaxshi bo'lsa meni yashаt, o'lim men uchun yaxshi bo'lsa mening jonim­ni ol.",
    transliteration: "Allaahummaa ahyinii maa kaanatil hayaatu khayran lii wa tawaffanii izaa kaanatil wafaatu khayran lii",
  },

  // ============ ERTALAB (Morning) ============
  {
    id: "e1",
    category: "ertalab",
    title: "Uyg'onishda",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
    uzbek: "Bizni o'ldirganidan keyin yana tiriltirgan va qaytish Unga bo'lgan Allohga hamd bo'lsin.",
    transliteration: "Alhamdulillaahillazii ahyaanaa ba'da maa amaatanaa wa ilayhin nushuur",
  },
  {
    id: "e2",
    category: "ertalab",
    title: "Ertalabgi zikr",
    arabic: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ",
    uzbek: "Biz ertalabga chiqdik va mulk Allohniki bo'lib ertalabga chiqdi. Hamd Allohga. Allohdan o'zga iloh yo'q, U yolg'iz va sherik yo'q.",
    transliteration: "Asbahnaa wa asbahal mulku lillaah, walhamdulillaah, laa ilaaha illallaahu wahdahu laa shariika lah",
  },
  {
    id: "e3",
    category: "ertalab",
    title: "Ertalabgi himoya",
    arabic: "اللَّهُمَّ بِكَ أَصْبَحْنَا وَبِكَ أَمْسَيْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ النُّشُورُ",
    uzbek: "Allohim! Sening bilan ertalabga chiqdik, Sening bilan kechga kiramiz, Sening bilan yashаymiz, Sening bilan o'lamiz va qaytish Sengadir.",
    transliteration: "Allaahummaa bika asbahnaa wa bika amsaynaa wa bika nahyaa wa bika namuutu wa ilaykan nushuur",
  },
  {
    id: "e4",
    category: "ertalab",
    title: "Kun boshida himoya",
    arabic: "بِسْمِ اللَّهِ الَّذِي لاَ يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الأَرْضِ وَلاَ فِي السَّمَاءِ",
    uzbek: "Allohning nomi bilan — Uning nomi bilan yer va osmonda hech narsa zarar yetkazolmaydi.",
    transliteration: "Bismillaahillazii laa yadurru ma'asmihi shay'un fil ardi wa laa fis samaa",
  },
  {
    id: "e5",
    category: "ertalab",
    title: "100 marta durud",
    arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ",
    uzbek: "Allohim! Muhammadga va Muhammad alayhissalomning ahliga salovat yubor.",
    transliteration: "Allaahummaa salli alaa Muhammadin wa alaa aali Muhammad",
  },
  {
    id: "e6",
    category: "ertalab",
    title: "Rivojlanish uchun",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا وَرِزْقًا طَيِّبًا وَعَمَلاً مُتَقَبَّلاً",
    uzbek: "Allohim! Sendan foydali ilm, halol rizq va qabul qilinadigan amal so'rayman.",
    transliteration: "Allaahummaa innii as'aluka ilman naafi'aw wa rizqan tayyibaw wa amalan mutaqabbalaa",
  },
  {
    id: "e7",
    category: "ertalab",
    title: "Afiyat so'rash",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ فِي الدُّنْيَا وَالآخِرَةِ",
    uzbek: "Allohim! Sendan dunyoda ham, oxiratda ham sog'-salomatlik so'rayman.",
    transliteration: "Allaahummaa innii as'alukal aafiyata fid-dunyaa wal aakhirah",
  },
  {
    id: "e8",
    category: "ertalab",
    title: "Rozililik",
    arabic: "رَضِيتُ بِاللَّهِ رَبًّا وَبِالْإِسْلاَمِ دِينًا وَبِمُحَمَّدٍ نَبِيًّا",
    uzbek: "Allohdan Rabb sifatida, Islomdan din sifatida va Muhammaddan payg'ambar sifatida rozi bo'ldim.",
    transliteration: "Radiitu billaahi Rabbaw wa bil Islaami diinaw wa bi Muhammadin nabiyyaa",
  },

  // ============ KECHQURUN (Evening) ============
  {
    id: "k1",
    category: "kechqurun",
    title: "Kechqurungi zikr",
    arabic: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ",
    uzbek: "Biz kechga kirdik, mulk Allohniki bo'lib kechga kirdi. Hamd Allohga. Allohdan o'zga iloh yo'q, U yolg'iz va sherik yo'q.",
    transliteration: "Amsaynaa wa amsal mulku lillaah, walhamdulillaah, laa ilaaha illallaahu wahdahu laa shariika lah",
  },
  {
    id: "k2",
    category: "kechqurun",
    title: "Kechqurungi himoya",
    arabic: "اللَّهُمَّ بِكَ أَمْسَيْنَا وَبِكَ أَصْبَحْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ الْمَصِيرُ",
    uzbek: "Allohim! Sening bilan kechga kirdik, Sening bilan ertalabga chiqamiz, Sening bilan yashаymiz va Sening bilan o'lamiz, qaytish Sengadir.",
    transliteration: "Allaahummaa bika amsaynaa wa bika asbahnaa wa bika nahyaa wa bika namuutu wa ilaykal masiir",
  },
  {
    id: "k3",
    category: "kechqurun",
    title: "Kechqurungi istighfor",
    arabic: "اللَّهُمَّ إِنِّي أَمْسَيْتُ أُشْهِدُكَ وَأُشْهِدُ حَمَلَةَ عَرْشِكَ وَمَلاَئِكَتَكَ وَجَمِيعَ خَلْقِكَ أَنَّكَ أَنْتَ اللَّهُ لاَ إِلَهَ إِلاَّ أَنْتَ وَحْدَكَ لاَ شَرِيكَ لَكَ",
    uzbek: "Allohim! Men kechga kirib Seni, Arshingni ko'taruvchilarni, farishtalaring va butun borlig'ingni guvoh qilib aytaman: Sen yolg'iz Allohsan, Sendan boshqa iloh yo'q, Sening sheriklaring yo'q.",
    transliteration: "Allaahummaa innii amsaytu ush-hiduka wa ush-hidu hamalata arshika wa malaa'ikataka wa jamii'a khalqika annaka antallaaahu laa ilaaha illaa anta wahdaka laa shariika lak",
  },
  {
    id: "k4",
    category: "kechqurun",
    title: "Kechqurungi 3 marta",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    uzbek: "Allohning mukammal so'zlari bilan yaratilgan narsalarning yomonligidan panoh tilayman.",
    transliteration: "A'uuzu bikalimaa tillaahit taammati min sharri maa khalaq",
  },
  {
    id: "k5",
    category: "kechqurun",
    title: "Kechani yaxshi o'tkazish",
    arabic: "بِسْمِكَ رَبِّي وَضَعْتُ جَنْبِي وَبِكَ أَرْفَعُهُ فَإِنْ أَمْسَكْتَ نَفْسِي فَارْحَمْهَا وَإِنْ أَرْسَلْتَهَا فَاحْفَظْهَا",
    uzbek: "Parvardigorim Sening isminng bilan yonboshladim, Sening bilan ko'taraman. Agar jonim ushlab olsang, unga rahm ayla; qo'ysang, uni asra.",
    transliteration: "Bismika rabbii wada'tu janbii wa bika arfa'uhu fa in amsakta nafsii farhamhaa wa in arsaltahaa fahfazha",
  },
  {
    id: "k6",
    category: "kechqurun",
    title: "Gunoh kechirilishi uchun",
    arabic: "اللَّهُمَّ اغْفِرْ لِي ذَنْبِي كُلَّهُ، دِقَّهُ وَجِلَّهُ، وَأَوَّلَهُ وَآخِرَهُ، وَعَلاَنِيَتَهُ وَسِرَّهُ",
    uzbek: "Allohim! Barcha gunohlarimni kechir — kichigini ham, kattagini ham, birinchisini ham, so'nggisini ham, oshkorasini ham, yashirinini ham.",
    transliteration: "Allaahummagh-fir lii dzanbii kullahu diqqahu wa jillahu wa awwalahu wa aakhirahu wa alaaniyatahu wa sirrahu",
  },
  {
    id: "k7",
    category: "kechqurun",
    title: "Sayyidul istigfar",
    arabic: "اللَّهُمَّ أَنْتَ رَبِّي لاَ إِلَهَ إِلاَّ أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي",
    uzbek: "Allohim! Sen mening Rabbimsan. Sendan boshqa iloh yo'q. Sen meni yaratding va men Sening quling. Qo'limdan kelgancha Sening ahdingga va va'dangga amalaman. Qilgan yomonliqlarim­ning yomonligidan Sening panohing olayman. Menga bergan ne'matingni tan olayman, gunohimni ham tan olayman. Meni kechir.",
    transliteration: "Allaahummaa anta rabbii laa ilaaha illaa anta, khalaqtanii wa anaa abduka, wa anaa alaa ahdika wa wa'dika mastata'tu, a'uuzu bika min sharri maa sana'tu, abuu'u laka bini'matika alayya, wa abuu'u bidzanbii faghfir lii",
  },

  // ============ OVQAT (Food) ============
  {
    id: "o1",
    category: "ovqat",
    title: "Ovqat oldin",
    arabic: "بِسْمِ اللَّهِ وَعَلَى بَرَكَةِ اللَّهِ",
    uzbek: "Allohning nomi bilan va Allohning barakasi bilan (boshlayman).",
    transliteration: "Bismillaahi wa alaa barakatillaah",
  },
  {
    id: "o2",
    category: "ovqat",
    title: "Ovqat unitsak",
    arabic: "بِسْمِ اللَّهِ فِي أَوَّلِهِ وَآخِرِهِ",
    uzbek: "Allohning nomi bilan — boshida ham oxirida ham.",
    transliteration: "Bismillaahi fii awwalihi wa aakhirih",
  },
  {
    id: "o3",
    category: "ovqat",
    title: "Ovqatdan keyin",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ",
    uzbek: "Bizni taomlantirib, suv ichirgan va bizni musulmon qilgan Allohga hamd bo'lsin.",
    transliteration: "Alhamdulillaahillazii at'amanaa wa saqaanaa wa ja'alanaa muslimiin",
  },
  {
    id: "o4",
    category: "ovqat",
    title: "Musofir uchun dua",
    arabic: "اللَّهُمَّ بَارِكْ لَهُمْ فِيمَا رَزَقْتَهُمْ وَاغْفِرْ لَهُمْ وَارْحَمْهُمْ",
    uzbek: "Allohim! Ularga bergan rizqingda baraka ber, ularni mag'firat qil va ularga rahm ayla.",
    transliteration: "Allaahummaa baarik lahum fiimaa razaqtahum waghfir lahum warhamhum",
  },
  {
    id: "o5",
    category: "ovqat",
    title: "Ro'za saharida",
    arabic: "نَوَيْتُ صَوْمَ غَدٍ عَنْ أَدَاءِ فَرْضِ شَهْرِ رَمَضَانَ هَذِهِ السَّنَةِ لِلَّهِ تَعَالَى",
    uzbek: "Men shu yilgi Ramazon oyining farzini ado etish uchun ertaga ro'za tutishga niyat qildim, Alloh taoloning rozoligini maqsad qilib.",
    transliteration: "Nawaytu sawma ghadin an adaa'i fardi shahri Ramadaana haazihis sanati lillaahi ta'aalaa",
  },
  {
    id: "o6",
    category: "ovqat",
    title: "Ro'za iftorida",
    arabic: "اللَّهُمَّ لَكَ صُمْتُ وَعَلَى رِزْقِكَ أَفْطَرْتُ",
    uzbek: "Allohim! Sening uchun ro'za tutdim va Sening rizqing bilan iftор qildim.",
    transliteration: "Allaahummaa laka sumtu wa alaa rizqika aftartu",
  },

  // ============ UYQU (Sleep) ============
  {
    id: "y1",
    category: "uyqu",
    title: "Uxlashdan oldin",
    arabic: "اللَّهُمَّ بِاسْمِكَ أَمُوتُ وَأَحْيَا",
    uzbek: "Allohim! Sening isming bilan o'laman va yashаyman.",
    transliteration: "Allaahummaa bismika amuutu wa ahyaa",
  },
  {
    id: "y2",
    category: "uyqu",
    title: "Yotishda",
    arabic: "بِاسْمِكَ اللَّهُمَّ أَحْيَا وَأَمُوتُ",
    uzbek: "Allohim! Sening isming bilan yashаyman va o'laman.",
    transliteration: "Bismikallaahummaa ahyaa wa amuut",
  },
  {
    id: "y3",
    category: "uyqu",
    title: "Tushdan oldin",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي كَفَانِي وَآوَانِي",
    uzbek: "Meni kifoya qilgan va boshpana bergan Allohga hamd bo'lsin.",
    transliteration: "Alhamdulillaahillazii kafaanii wa aawanaii",
  },
  {
    id: "y4",
    category: "uyqu",
    title: "Tush ko'rganda",
    arabic: "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ وَمِنْ شَرِّ هَذِهِ الرُّؤْيَا",
    uzbek: "Hay qilingan shaytondан va shu tushimning yomonligidan Allohning panohi­ga kiraman.",
    transliteration: "A'uuzubillaahi minash-shaytaanir rajiim wa min sharri haazihir ru'yaa",
  },
  {
    id: "y5",
    category: "uyqu",
    title: "Uyg'onganda duo",
    arabic: "اَلْحَمْدُ لِلَّهِ الَّذِي رَدَّ عَلَيَّ رُوحِي وَعَافَانِي فِي جَسَدِي وَأَذِنَ لِي بِذِكْرِهِ",
    uzbek: "Mening jonim­ni qaytargan, tanimni sog' qilgan va Oʻzini zikr etishga ruxsat bergan Allohga hamd bo'lsin.",
    transliteration: "Alhamdulillaahillazii radda alayya ruuhii wa aafaanii fii jasadii wa azina lii bizikrik",
  },

  // ============ SAFAR (Travel) ============
  {
    id: "s1",
    category: "safar",
    title: "Safarga chiqishda",
    arabic: "بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، وَلاَ حَوْلَ وَلاَ قُوَّةَ إِلاَّ بِاللَّهِ",
    uzbek: "Allohning nomi bilan. Allohga tavakkal qildim. Allohdan boshqa kuch va quvvat yo'q.",
    transliteration: "Bismillaah, tawakkaltu alallaaah, wa laa hawla wa laa quwwata illaa billaah",
  },
  {
    id: "s2",
    category: "safar",
    title: "Ulovga minishda",
    arabic: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ",
    uzbek: "Buni bizga bo'ysundirgan va biz buni mahkam ushlay olmaydigan bo'lsak ham, biz albatta Rabbimizga qaytuvchimiz, degan zot pok.",
    transliteration: "Subhaanallazhii sakhkhara lanaa haazaa wa maa kunnaa lahu muqriniina wa innaa ilaa rabbinaa lamunqalibuun",
  },
  {
    id: "s3",
    category: "safar",
    title: "Safar duosi",
    arabic: "اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَى وَمِنَ الْعَمَلِ مَا تَرْضَى",
    uzbek: "Allohim! Shu safarimizda yaxshilik, taqvo va Senga manzur bo'ladigan amal so'rayman.",
    transliteration: "Allaahummaa innaa nas'aluka fii safarinaa haazal birra wat-taqwaa wa minal amali maa tardaa",
  },
  {
    id: "s4",
    category: "safar",
    title: "Yangi shaharga kirishda",
    arabic: "اللَّهُمَّ بَارِكْ لَنَا فِيهَا",
    uzbek: "Allohim! Bu (shaharda) bizga baraka ber.",
    transliteration: "Allaahummaa baarik lanaa fiihaa",
  },
  {
    id: "s5",
    category: "safar",
    title: "Qaytishda",
    arabic: "آيِبُونَ تَائِبُونَ عَابِدُونَ لِرَبِّنَا حَامِدُونَ",
    uzbek: "Qaytuvchimiz, tavbachi, ibodat qiluvchi va Rabbimizga hamd aytuvchimiz.",
    transliteration: "Aa'ibuuna taa'ibuuna aabiduuna li-rabbinaa haamiduun",
  },
];
