export type DuaCategory = "umumiy" | "ertalab" | "kechqurun" | "ovqat" | "uyqu" | "safar";

export interface Dua {
  id: string;
  category: DuaCategory;
  title: string;
  titleUz: string;
  titleRu: string;
  titleEn: string;
  arabic: string;
  uzbek: string;
  transliteration: string;
}

export const DUA_CATEGORIES: Array<{ key: DuaCategory; label: string }> = [
  { key: "umumiy",   label: "Умумий"   },
  { key: "ertalab",  label: "Эрталаб"  },
  { key: "kechqurun",label: "Кечқурун" },
  { key: "ovqat",    label: "Овқат"    },
  { key: "uyqu",     label: "Уйқу"     },
  { key: "safar",    label: "Сафар"    },
];

export const DUAS: Dua[] = [
  // ============ UMUMIY ============
  {
    id: "u1",
    category: "umumiy",
    title: "Bismillah",
    titleUz: "Бисмиллаҳ",
    titleRu: "Бисмиллях",
    titleEn: "Bismillah",
    arabic: "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ",
    uzbek: "Аллоҳ номи билан бошлайман, У Меҳрибон ва Раҳимлидир.",
    transliteration: "Bismillaahir rahmaanir rahiim",
  },
  {
    id: "u2",
    category: "umumiy",
    title: "Istighfor",
    titleUz: "Истиғфор",
    titleRu: "Истигфар",
    titleEn: "Istighfar",
    arabic: "أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ",
    uzbek: "Буюк, Ҳайй ва Қаййум Аллоҳдан мағфират сўрайман ва Унга тавба қиламан.",
    transliteration: "Astaghfirullaah al-'aziim allazii laa ilaaha illaa huwal hayyul qayyoomu wa atuubu ilayh",
  },
  {
    id: "u3",
    category: "umumiy",
    title: "Quvvat va kuch uchun",
    titleUz: "Қувват ва куч учун",
    titleRu: "Для силы и мощи",
    titleEn: "For strength",
    arabic: "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    uzbek: "Куч ва қувват фақат Аллоҳ биландир.",
    transliteration: "Laa hawla wa laa quwwata illaa billaah",
  },
  {
    id: "u4",
    category: "umumiy",
    title: "Ota-ona uchun dua",
    titleUz: "Ота-она учун дуо",
    titleRu: "Дуа за родителей",
    titleEn: "Dua for parents",
    arabic: "رَّبِّ اغْفِرْ لِي وَلِوَالِدَيَّ وَارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
    uzbek: "Раббим! Мени ва ота-онамни кечир ва мени кичкина пайтда тарбиялаганлари учун уларга раҳм қил.",
    transliteration: "Rabbigh-fir lii wa liwaalidayya warhamhumaa kamaa rabbayaanii saghiiraa",
  },
  {
    id: "u5",
    category: "umumiy",
    title: "Hidoyat uchun",
    titleUz: "Ҳидоят учун",
    titleRu: "Для наставления",
    titleEn: "For guidance",
    arabic: "اللَّهُمَّ اهْدِنَا فِيمَنْ هَدَيْتَ",
    uzbek: "Аллоҳим! Ҳидоят берганларингни ҳидоят этгандек, мени ҳам ҳидоят эт.",
    transliteration: "Allaahummah-dinaa fiiman hadayt",
  },
  {
    id: "u6",
    category: "umumiy",
    title: "Sabr uchun",
    titleUz: "Сабр учун",
    titleRu: "Для терпения",
    titleEn: "For patience",
    arabic: "رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَتَوَفَّنَا مُسْلِمِينَ",
    uzbek: "Раббимиз! Бизга сабр бергин ва мусулмон ҳолда вафот эттиргин.",
    transliteration: "Rabbanaa afrigh 'alaynaa sabran wa tawaffanaa muslimiin",
  },
  {
    id: "u7",
    category: "umumiy",
    title: "Dunyo va oxirat uchun",
    titleUz: "Дунё ва охират учун",
    titleRu: "За этот мир и ахырат",
    titleEn: "For this world and hereafter",
    arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    uzbek: "Раббимиз! Бизга дунёда ва охиратда яхшилик бер ва дўзах азобидан бизни асра.",
    transliteration: "Rabbanaa aatinaa fid-dunyaa hasanatan wa fil-aakhirati hasanatan wa qinaa 'azaaban-naar",
  },
  {
    id: "u8",
    category: "umumiy",
    title: "Qo'rquv va g'amdan panoh",
    titleUz: "Қўрқув ва ғамдан паноҳ",
    titleRu: "Защита от страха и горя",
    titleEn: "Protection from fear and grief",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ وَالْعَجْزِ وَالْكَسَلِ وَالْبُخْلِ وَالدَّيْنِ وَغَلَبَةِ الرِّجَالِ",
    uzbek: "Аллоҳим! Хавотир, қайғу, ожизлик, ялқовлик, хасислик, қарз ва одамлар зулмидан Сенинг паноҳингни оламан.",
    transliteration: "Allaahummaa innii a'uuzu bika minal-hammi wal-hazani wal-'ajzi wal-kasali wal-bukhli wad-dayni wa ghalabatir-rijaal",
  },
  {
    id: "u9",
    category: "umumiy",
    title: "Yaxshi axloq uchun",
    titleUz: "Яхши ахлоқ учун",
    titleRu: "Для хорошего нрава",
    titleEn: "For good character",
    arabic: "اللَّهُمَّ حَسِّنْ خُلُقِي",
    uzbek: "Аллоҳим! Хулқимни чиройли қилгин.",
    transliteration: "Allaahummaa hassin khuluqii",
  },
  {
    id: "u10",
    category: "umumiy",
    title: "Dilni pok qilish",
    titleUz: "Дилни поклаш",
    titleRu: "Очищение сердца",
    titleEn: "Purifying the heart",
    arabic: "اللَّهُمَّ طَهِّرْ قَلْبِي مِنَ النِّفَاقِ وَعَمَلِي مِنَ الرِّيَاءِ",
    uzbek: "Аллоҳим! Дилимни нифоқдан ва амалимни риёдан поклагин.",
    transliteration: "Allaahummaa tahhir qalbii minan-nifaaqi wa 'amalii minar-riyaa'",
  },
  {
    id: "u11",
    category: "umumiy",
    title: "Ilm uchun",
    titleUz: "Илм учун",
    titleRu: "Для знаний",
    titleEn: "For knowledge",
    arabic: "رَّبِّ زِدْنِي عِلْمًا",
    uzbek: "Раббим! Илмимни зиёда қилгин.",
    transliteration: "Rabbi zidnii 'ilmaa",
  },
  {
    id: "u12",
    category: "umumiy",
    title: "Rizq uchun",
    titleUz: "Ризқ учун",
    titleRu: "Для пропитания",
    titleEn: "For provision",
    arabic: "اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ",
    uzbek: "Аллоҳим! Ҳалолинг билан ҳаромдан мени беҳожат қилгин.",
    transliteration: "Allaahummak-finii bihalaalika 'an haraamik",
  },
  {
    id: "u13",
    category: "umumiy",
    title: "Tawba va kechirish",
    titleUz: "Тавба ва кечириш",
    titleRu: "Покаяние и прощение",
    titleEn: "Repentance and forgiveness",
    arabic: "اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي",
    uzbek: "Аллоҳим! Сен кечирувчисан ва кечиришни яхши кўрасан, мени кечиргин.",
    transliteration: "Allaahummaa innaka 'afuwwun tuhibbul-'afwa fa'fu 'annii",
  },
  {
    id: "u14",
    category: "umumiy",
    title: "Sog'lik uchun",
    titleUz: "Соғлиқ учун",
    titleRu: "Для здоровья",
    titleEn: "For health",
    arabic: "اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي",
    uzbek: "Аллоҳим! Танамга соғлиқ бер. Аллоҳим! Эшитишимga соғлиқ бер. Аллоҳим! Кўришимga соғлиқ бер.",
    transliteration: "Allaahummaa 'aafini fii badanii, Allaahummaa 'aafini fii sam'ii, Allaahummaa 'aafini fii basarii",
  },
  {
    id: "u15",
    category: "umumiy",
    title: "Ishni osonlashtirish",
    titleUz: "Ишни осонлаштириш",
    titleRu: "Облегчение дел",
    titleEn: "Ease of affairs",
    arabic: "رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي",
    uzbek: "Раббим! Кўкрагимни кенг қилгин ва ишимни осонлаштиргин.",
    transliteration: "Rabbish-rah lii sadrii wa yassir lii amrii",
  },
  {
    id: "u16",
    category: "umumiy",
    title: "Hidoyat, taqvo va iffat",
    titleUz: "Ҳидоят, тақво ва иффат",
    titleRu: "Наставление, богобоязнь и целомудрие",
    titleEn: "Guidance, piety and chastity",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْهُدَى وَالتُّقَى وَالْعَفَافَ وَالْغِنَى",
    uzbek: "Аллоҳим! Сендан ҳидоят, тақво, иффат ва бойлик сўрайман.",
    transliteration: "Allaahummaa innii as'alukal hudaa wat-tuqaa wal-'afaafa wal-ghinaa",
  },
  {
    id: "u17",
    category: "umumiy",
    title: "Qarzdan xalos bo'lish",
    titleUz: "Қарздан халос бўлиш",
    titleRu: "Освобождение от долга",
    titleEn: "Freedom from debt",
    arabic: "اللَّهُمَّ اكْفِنِي بِحَلاَلِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ",
    uzbek: "Аллоҳим! Ҳалолинг билан ҳаромдан мени асра ва Сенинг фазлинг билан бошқаларга муҳтож этма.",
    transliteration: "Allaahummak-finii bihalaalika 'an haraamika wa aghnii bifadlika 'amman siwaak",
  },
  {
    id: "u18",
    category: "umumiy",
    title: "Jannat uchun",
    titleUz: "Жаннат учун",
    titleRu: "Для Рая",
    titleEn: "For Paradise",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْجَنَّةَ وَمَا قَرَّبَ إِلَيْهَا مِنْ قَوْلٍ أَوْ عَمَلٍ",
    uzbek: "Аллоҳим! Сендан жаннатни ва унга яқинлаштирувчи сўз ва амалларни сўрайман.",
    transliteration: "Allaahummaa innii as'alukal jannata wa maa qarraba ilayhaa min qawlin aw 'amal",
  },
  {
    id: "u19",
    category: "umumiy",
    title: "Do'zaxdan panoh",
    titleUz: "Дўзахдан паноҳ",
    titleRu: "Защита от Ада",
    titleEn: "Protection from Hellfire",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ النَّارِ وَمَا قَرَّبَ إِلَيْهَا مِنْ قَوْلٍ أَوْ عَمَلٍ",
    uzbek: "Аллоҳим! Дўзахдан ва унга яқинлаштирувчи сўз ва амалларидан Сенинг паноҳингни оламан.",
    transliteration: "Allaahummaa innii a'uuzu bika minan-naari wa maa qarraba ilayhaa min qawlin aw 'amal",
  },
  {
    id: "u20",
    category: "umumiy",
    title: "Oilaga baraka",
    titleUz: "Оилага барака",
    titleRu: "Благословение семьи",
    titleEn: "Blessing for the family",
    arabic: "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا",
    uzbek: "Раббимиз! Бизга жуфтлар ва фарзандлардан кўзимизнинг қувончини бергин ва бизни тақводорларнинг имоми қилгин.",
    transliteration: "Rabbanaa hab lanaa min azwaajinaa wa zurriyyaatinaa qurrata a'yunin waj'alnaa lil-muttaqiina imaaman",
  },

  // ============ ERTALAB ============
  {
    id: "e1",
    category: "ertalab",
    title: "Uyg'onganda",
    titleUz: "Уйғонганда",
    titleRu: "При пробуждении",
    titleEn: "Upon waking up",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
    uzbek: "Бизни ўлдиргандан сўнг тирилтирган Аллоҳга ҳамд бўлсин. Қайта тириш У зотники!",
    transliteration: "Alhamdulillaahil-lazii ahyaanaa ba'da maa amaatanaa wa ilayhin-nushuur",
  },
  {
    id: "e2",
    category: "ertalab",
    title: "Ertalab zikri",
    titleUz: "Эрталаб зикри",
    titleRu: "Утренний зикр",
    titleEn: "Morning dhikr",
    arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ عَدَدَ خَلْقِهِ وَرِضَا نَفْسِهِ وَزِنَةَ عَرْشِهِ وَمِدَادَ كَلِمَاتِهِ",
    uzbek: "Аллоҳни яратган нарсаларининг сони, ўзининг розилиги, Аршининг оғирлиги ва Калималарининг миқдори билан поклайман ва Унга ҳамд айтаман.",
    transliteration: "Subhaanallaahi wa bihamdihii 'adada khalqihii wa ridaa nafsihii wa zinata 'arshihii wa midaada kalimaaatih",
  },
  {
    id: "e3",
    category: "ertalab",
    title: "Sayyidul-Istighfor",
    titleUz: "Саййидул-Истиғфор",
    titleRu: "Господин истигфаров",
    titleEn: "Sayyidul-Istighfar",
    arabic: "اللَّهُمَّ أَنْتَ رَبِّي لاَ إِلَهَ إِلاَّ أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ",
    uzbek: "Аллоҳим! Сен менинг Раббимсан, Сендан бошqa илоҳ йўқ. Сен мени яратдинг ва мен Сенинг бандангман.",
    transliteration: "Allaahummaa anta rabbii laa ilaaha illaa anta khalaqtanii wa anaa 'abduk",
  },
  {
    id: "e4",
    category: "ertalab",
    title: "Ertalab panoh so'rash",
    titleUz: "Эрталаб паноҳ сўраш",
    titleRu: "Утренняя защита",
    titleEn: "Morning protection",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    uzbek: "Яратганларнинг yомонлигидан Аллоҳнинг комил сўзлари билан паноҳ тилайман.",
    transliteration: "A'uuzu bikalimaat-illaahit-taammaati min sharri maa khalaq",
  },
  {
    id: "e5",
    category: "ertalab",
    title: "Ertalab duosi",
    titleUz: "Эрталаб дуоси",
    titleRu: "Утренняя молитва-дуа",
    titleEn: "Morning dua",
    arabic: "اللَّهُمَّ بِكَ أَصْبَحْنَا وَبِكَ أَمْسَيْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ الْمَصِيرُ",
    uzbek: "Аллоҳим! Сенинг ёрдаминг билан тонг оттирдик, кечқурун кирдик, яшаймиз, ўламиз ва қайтиш ёлғиз Сенга.",
    transliteration: "Allaahummaa bika asbahnaa wa bika amsaynaa wa bika nahyaa wa bika namuutu wa ilaykal-masiir",
  },
  {
    id: "e6",
    category: "ertalab",
    title: "Radda qilish kalimasi",
    titleUz: "Радда қилиш калимаси",
    titleRu: "Слово отречения",
    titleEn: "Word of negation",
    arabic: "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
    uzbek: "Аллоҳдан бошqa илоҳ йўқ, У якка, шериксиз. Мулк Уники, ҳамд Уники ва У ҳар нарсага Қодирдир.",
    transliteration: "Laa ilaaha illallaahu wahdahu laa shariika lah, lahul-mulku wa lahul-hamdu wa huwa 'alaa kulli shay'in qadiir",
  },
  {
    id: "e7",
    category: "ertalab",
    title: "Bismillah bilan kiyinishda",
    titleUz: "Бисмиллаҳ билан кийинишда",
    titleRu: "При одевании",
    titleEn: "When getting dressed",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ خَيْرِهِ وَخَيْرِ مَا هُوَ لَهُ وَأَعُوذُ بِكَ مِنْ شَرِّهِ وَشَرِّ مَا هُوَ لَهُ",
    uzbek: "Аллоҳим! Сендан бу нарсанинг хайрини ва у учун ҳасиллашган хайрни сўрайман, ёмонлигидан ва у учун ҳасиллашган ёмонликдан Сенинг паноҳингни оламан.",
    transliteration: "Allaahummaa innii as'aluka min khayrihi wa khayri maa huwa lahu wa a'uuzu bika min sharrihi wa sharri maa huwa lah",
  },
  {
    id: "e8",
    category: "ertalab",
    title: "Tong otganda",
    titleUz: "Тонг отганда",
    titleRu: "На рассвете",
    titleEn: "At dawn",
    arabic: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ وَلَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ",
    uzbek: "Биз ва бутун мулк Аллоҳнинг ёрдамида тонг оттирдик. Ҳамд Аллоҳга, Унга бошqa илоҳ йўқ, У якка ва шериксиздир.",
    transliteration: "Asbahnaa wa asbahal-mulku lillaahi walhamdu lillaahi wa laa ilaaha illallaahu wahdahu laa shariika lah",
  },
  {
    id: "e9",
    category: "ertalab",
    title: "Subh namozidan keyin",
    titleUz: "Субҳ намозидан кейин",
    titleRu: "После утреннего намаза",
    titleEn: "After Fajr prayer",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا وَرِزْقًا طَيِّبًا وَعَمَلاً مُتَقَبَّلاً",
    uzbek: "Аллоҳим! Сендан фойдали илм, ҳалол ризқ ва қабул қилинадиган амал сўрайман.",
    transliteration: "Allaahummaa innii as'aluka 'ilman naafi'an wa rizqan tayyiban wa 'amalan mutaqabbalan",
  },
  {
    id: "e10",
    category: "ertalab",
    title: "Yangi kun boshida",
    titleUz: "Янги кун бошида",
    titleRu: "В начале нового дня",
    titleEn: "Start of a new day",
    arabic: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ عَلَيْكَ تَوَكَّلْتُ وَأَنْتَ رَبُّ الْعَرْشِ الْعَظِيمِ",
    uzbek: "Аллоҳим! Сен менинг Раббимсан. Сендан бошqa илоҳ йўқ. Сенга таваккал қилдим. Сен Улуғ Аршнинг Раббисан.",
    transliteration: "Allaahummaa anta rabbii laa ilaaha illaa anta 'alayka tawakkaltu wa anta rabbul-'arshil-'aziim",
  },

  // ============ KECHQURUN ============
  {
    id: "k1",
    category: "kechqurun",
    title: "Kechqurun duosi",
    titleUz: "Кечқурун дуоси",
    titleRu: "Вечерняя молитва-дуа",
    titleEn: "Evening dua",
    arabic: "اللَّهُمَّ بِكَ أَمْسَيْنَا وَبِكَ أَصْبَحْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ الْمَصِيرُ",
    uzbek: "Аллоҳим! Сенинг ёрдаминг билан кечқурун кирдик, тонг оттирдик, яшаймиз, ўламиз ва қайтиш ёлғиз Сенга.",
    transliteration: "Allaahummaa bika amsaynaa wa bika asbahnaa wa bika nahyaa wa bika namuutu wa ilaykal-masiir",
  },
  {
    id: "k2",
    category: "kechqurun",
    title: "Gunohlardan tavba",
    titleUz: "Гуноҳлардан тавба",
    titleRu: "Покаяние в грехах",
    titleEn: "Repentance from sins",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ وَمِنْ عَذَابِ النَّارِ",
    uzbek: "Аллоҳим! Қабр азобидан ва дўзах азобидан Сенинг паноҳингни оламан.",
    transliteration: "Allaahummaa innii a'uuzu bika min 'azaabil-qabri wa min 'azaabin-naar",
  },
  {
    id: "k3",
    category: "kechqurun",
    title: "Kechqurun zikri",
    titleUz: "Кечқурун зикри",
    titleRu: "Вечерний зикр",
    titleEn: "Evening dhikr",
    arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
    uzbek: "Аллоҳ поктир ва ҳамд У учундир. (100 марта)",
    transliteration: "Subhaanallaahi wa bihamdih",
  },
  {
    id: "k4",
    category: "kechqurun",
    title: "Barcha jonzodlardan panoh",
    titleUz: "Барча жонзодлардан паноҳ",
    titleRu: "Защита от всех творений",
    titleEn: "Protection from all creation",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    uzbek: "Яратганларнинг ёмонлигидан Аллоҳнинг комил сўзлари билан паноҳ тилайман.",
    transliteration: "A'uuzu bikalimaat-illaahit-taammaati min sharri maa khalaq",
  },
  {
    id: "k5",
    category: "kechqurun",
    title: "Shaytondan panoh",
    titleUz: "Шайтондан паноҳ",
    titleRu: "Защита от шайтана",
    titleEn: "Protection from shaytan",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الشَّيْطَانِ الرَّجِيمِ",
    uzbek: "Аллоҳим! Қувилган шайтондан Сенинг паноҳингни оламан.",
    transliteration: "Allaahummaa innii a'uuzu bika minash-shaytaanir-rajiim",
  },
  {
    id: "k6",
    category: "kechqurun",
    title: "Kechadan omonsiz qolmaslik uchun",
    titleUz: "Кечадан омонсиз қолмаслик учун",
    titleRu: "Защита в ночное время",
    titleEn: "Safety through the night",
    arabic: "اللَّهُمَّ عَالِمَ الْغَيْبِ وَالشَّهَادَةِ فَاطِرَ السَّمَاوَاتِ وَالأَرْضِ",
    uzbek: "Аллоҳим! Ғайб ва ошкорни Билувчи, Осмонлар ва Ернинг Яратувчиси.",
    transliteration: "Allaahummaa 'aalimal-ghaybi wash-shahaadati faatiris-samaawaati wal-ard",
  },
  {
    id: "k7",
    category: "kechqurun",
    title: "Dillarga shukr",
    titleUz: "Дилларга шукр",
    titleRu: "Благодарность сердцем",
    titleEn: "Gratitude of the heart",
    arabic: "اللَّهُمَّ مَا أَمْسَى بِي مِنْ نِعْمَةٍ أَوْ بِأَحَدٍ مِنْ خَلْقِكَ فَمِنْكَ وَحْدَكَ",
    uzbek: "Аллоҳим! Мен ёки бандаларингdan биriga тушган барча неъмат фақат Сендандир.",
    transliteration: "Allaahummaa maa amsaa bii min ni'matin aw bi-ahadin min khalqika faminka wahdak",
  },
  {
    id: "k8",
    category: "kechqurun",
    title: "Yotishdan oldin zikr",
    titleUz: "Ётишдан олдин зикр",
    titleRu: "Зикр перед сном",
    titleEn: "Dhikr before sleep",
    arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
    uzbek: "Аллоҳ поктир ва ҳамд У учундир. (30 марта)",
    transliteration: "Subhaanallaahi wa bihamdih",
  },

  // ============ OVQAT ============
  {
    id: "o1",
    category: "ovqat",
    title: "Ovqat oldidan",
    titleUz: "Овқат олдидан",
    titleRu: "Перед едой",
    titleEn: "Before eating",
    arabic: "بِسْمِ اللَّهِ وَعَلَى بَرَكَةِ اللَّهِ",
    uzbek: "Аллоҳ номи ва Аллоҳнинг барака билан (бошлайман).",
    transliteration: "Bismillaahi wa 'alaa barakatillaah",
  },
  {
    id: "o2",
    category: "ovqat",
    title: "Ovqatni unutib boshlaganida",
    titleUz: "Овқатни унутиб бошлаганда",
    titleRu: "Если забыл начать с басмалы",
    titleEn: "If forgot to say Bismillah",
    arabic: "بِسْمِ اللَّهِ فِي أَوَّلِهِ وَآخِرِهِ",
    uzbek: "Аллоҳ номи билан бошида ва охирида.",
    transliteration: "Bismillaahi fii awwalihi wa aakhirih",
  },
  {
    id: "o3",
    category: "ovqat",
    title: "Ovqatdan keyin",
    titleUz: "Овқатдан кейин",
    titleRu: "После еды",
    titleEn: "After eating",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ",
    uzbek: "Бизни таомлантирган, суғорган ва мусулмонлардан қилган Аллоҳга ҳамд бўлсин.",
    transliteration: "Alhamdulillaahil-lazii at'amanaa wa saqaanaa wa ja'alnaa muslimiin",
  },
  {
    id: "o4",
    category: "ovqat",
    title: "Ro'za iftorida",
    titleUz: "Рўза ифторида",
    titleRu: "При разговении",
    titleEn: "Breaking the fast",
    arabic: "اللَّهُمَّ لَكَ صُمْتُ وَعَلَى رِزْقِكَ أَفْطَرْتُ",
    uzbek: "Аллоҳим! Сен учун рўза тутдим ва Сенинг ризқинг билан ифтор қилдим.",
    transliteration: "Allaahummaa laka sumtu wa 'alaa rizqika aftart",
  },
  {
    id: "o5",
    category: "ovqat",
    title: "Mehmonni kuzatishda",
    titleUz: "Меҳмонни кузатишда",
    titleRu: "При проводах гостя",
    titleEn: "Seeing off a guest",
    arabic: "أَكَلَ طَعَامَكُمُ الأَبْرَارُ وَصَلَّتْ عَلَيْكُمُ الْمَلَائِكَةُ وَأَفْطَرَ عِنْدَكُمُ الصَّائِمُونَ",
    uzbek: "Яхшилар сизнинг таомингизни есин, фаришталар сизга салавот айтсин ва рўзадорлар сизникида ифтор қилсин.",
    transliteration: "Akala ta'aamakumul-abraaru wa sallat 'alaykumul-malaa'ikatu wa aftara 'indakumus-saa'imuun",
  },
  {
    id: "o6",
    category: "ovqat",
    title: "Suvni ichishda",
    titleUz: "Сувни ичишда",
    titleRu: "При питье воды",
    titleEn: "When drinking water",
    arabic: "بِسْمِ اللَّهِ",
    uzbek: "Аллоҳ номи билан.",
    transliteration: "Bismillaah",
  },
  {
    id: "o7",
    category: "ovqat",
    title: "Iftor duosi",
    titleUz: "Ифтор дуоси",
    titleRu: "Дуа разговения",
    titleEn: "Iftar dua",
    arabic: "ذَهَبَ الظَّمَأُ وَابْتَلَّتِ الْعُرُوقُ وَثَبَتَ الأَجْرُ إِنْ شَاءَ اللَّهُ",
    uzbek: "Чанқоқлик кетди, томирлар намланди ва ажр — Аллоҳ хоҳлаganда — собит бўлди.",
    transliteration: "Zahabaz-zama'u wabtallatil-'uruuqu wa thabatal-ajru in-shaa'allaah",
  },

  // ============ UYQU ============
  {
    id: "y1",
    category: "uyqu",
    title: "Yotishdan oldin",
    titleUz: "Ётишдан олдин",
    titleRu: "Перед сном",
    titleEn: "Before sleeping",
    arabic: "بِسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
    uzbek: "Аллоҳим! Сенинг номинг билан ўламан ва тириламан.",
    transliteration: "Bismikallaahumma amuutu wa ahyaa",
  },
  {
    id: "y2",
    category: "uyqu",
    title: "Yotishda o'ng yonga yotib",
    titleUz: "Ётишда ўнг ёнга ётиб",
    titleRu: "Ложась на правый бок",
    titleEn: "Lying on the right side",
    arabic: "اللَّهُمَّ إِنِّي أَسْلَمْتُ نَفْسِي إِلَيْكَ وَوَجَّهْتُ وَجْهِي إِلَيْكَ",
    uzbek: "Аллоҳим! Мен ўзимни Сенга топшира ва юзимни Сенга бурдим.",
    transliteration: "Allaahummaa innii aslamtu nafsii ilayka wa wajjahtu wajhii ilayk",
  },
  {
    id: "y3",
    category: "uyqu",
    title: "Yomon tushdan keyin",
    titleUz: "Ёмон тушдан кейин",
    titleRu: "После плохого сна",
    titleEn: "After a bad dream",
    arabic: "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ",
    uzbek: "Мен қувилган шайтондан Аллоҳнинг паноҳини тилайман.",
    transliteration: "A'uuzu billaahi minash-shaytaanir-rajiim",
  },
  {
    id: "y4",
    category: "uyqu",
    title: "Uyquga ketishda 3 marta",
    titleUz: "Уйқуга кетишда 3 марта",
    titleRu: "Перед сном 3 раза",
    titleEn: "Before sleep 3 times",
    arabic: "سُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ وَاللَّهُ أَكْبَرُ",
    uzbek: "Аллоҳ поктир, ҳамд Аллоҳга ва Аллоҳ улуғдир. (33 марта)",
    transliteration: "Subhaanallaahi walhamdu lillaahi wallaahu akbar",
  },
  {
    id: "y5",
    category: "uyqu",
    title: "Al-Mulk surasi",
    titleUz: "Мулк сураси",
    titleRu: "Сура Аль-Мульк",
    titleEn: "Surah Al-Mulk",
    arabic: "تَبَارَكَ الَّذِي بِيَدِهِ الْمُلْكُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
    uzbek: "Мулк Ўз қўлида бўлган ва ҳар нарсага Қодир бўлган Аллоҳ баракотлидир.",
    transliteration: "Tabaarakal-lazii biyadihil-mulku wa huwa 'alaa kulli shay'in qadiir",
  },
  {
    id: "y6",
    category: "uyqu",
    title: "Tun o'rtasida uyg'onganda",
    titleUz: "Тун ўртасида уйғонганда",
    titleRu: "При пробуждении ночью",
    titleEn: "Waking up at night",
    arabic: "لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
    uzbek: "Аллоҳдан бошqa илоҳ йўқ, У якка ва шериксиз. Мулк Уники, ҳамд Уники ва У ҳар нарсага Қодирдир.",
    transliteration: "Laa ilaaha illallaahu wahdahu laa shariika lah, lahul-mulku wa lahul-hamdu wa huwa 'alaa kulli shay'in qadiir",
  },
  {
    id: "y7",
    category: "uyqu",
    title: "Uxlashdan oldin Ayat ul-Kursi",
    titleUz: "Ухлашдан олдин Оятул-Курси",
    titleRu: "Аятуль-Курси перед сном",
    titleEn: "Ayatul-Kursi before sleep",
    arabic: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ",
    uzbek: "Аллоҳ — Ундан бошqa илоҳ йўқ, Тирик ва Барқарор Зот.",
    transliteration: "Allaahu laa ilaaha illaa huwal-hayyul-qayyuum",
  },

  // ============ SAFAR ============
  {
    id: "s1",
    category: "safar",
    title: "Safarga otlanishda",
    titleUz: "Сафарга отланишда",
    titleRu: "Отправляясь в путь",
    titleEn: "Setting off on a journey",
    arabic: "اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَى",
    uzbek: "Аллоҳим! Бу сафаримизда Сендан яхшилик ва тақво сўраймиз.",
    transliteration: "Allaahummaa innaa nas'aluka fii safarinaa haazal-birra wat-taqwaa",
  },
  {
    id: "s2",
    category: "safar",
    title: "Uydan chiqishda",
    titleUz: "Уйдан чиқишда",
    titleRu: "При выходе из дома",
    titleEn: "Leaving the house",
    arabic: "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ، لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    uzbek: "Аллоҳ номи билан, Аллоҳга таваккал қилдим, куч ва қувват фақат Аллоҳ биландир.",
    transliteration: "Bismillaahi tawakkaltu 'alallaahi laa hawla wa laa quwwata illaa billaah",
  },
  {
    id: "s3",
    category: "safar",
    title: "Transport vositasiga minishda",
    titleUz: "Транспорт воситасига минишда",
    titleRu: "При посадке в транспорт",
    titleEn: "Boarding transportation",
    arabic: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ",
    uzbek: "Буни бизга бўйсундирган Аллоҳ поктир, биз уни бўйсундира олмаsdik. Биз Раббимизга қайтамиз.",
    transliteration: "Subhaanalazii sakhkhara lanaa haazaa wa maa kunnaa lahu muqriniina wa innaa ilaa rabbinaa lamunqalibuun",
  },
  {
    id: "s4",
    category: "safar",
    title: "Yangi shaharga kirishda",
    titleUz: "Янги шаҳарга киришда",
    titleRu: "При въезде в новый город",
    titleEn: "Entering a new city",
    arabic: "اللَّهُمَّ بَارِكْ لَنَا فِيهَا",
    uzbek: "Аллоҳим! Бу шаҳарда бизга барака бергин.",
    transliteration: "Allaahummaa baarik lanaa fiihaa",
  },
  {
    id: "s5",
    category: "safar",
    title: "Qaytishda",
    titleUz: "Қайтишда",
    titleRu: "При возвращении",
    titleEn: "Upon returning",
    arabic: "آيِبُونَ تَائِبُونَ عَابِدُونَ لِرَبِّنَا حَامِدُونَ",
    uzbek: "Қайтувчимиз, тавбачимиз, ибодат қилувчимиз ва Раббимизга ҳамд айтувчимиз.",
    transliteration: "Aa'ibuuna taa'ibuuna 'aabiduuna li-rabbinaa haamiduun",
  },
  {
    id: "s6",
    category: "safar",
    title: "Mashinaga minishda",
    titleUz: "Машинага минишда",
    titleRu: "При посадке в машину",
    titleEn: "Getting into a car",
    arabic: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ",
    uzbek: "Буни бизга бўйсундирган Аллоҳ поктир, биз уни маҳкам ушлай олмасdик.",
    transliteration: "Subhaanallazii sakhkhara lanaa haazaa wa maa kunnaa lahu muqriniin",
  },
  {
    id: "s7",
    category: "safar",
    title: "Safar mashaqqatlaridan",
    titleUz: "Сафар машаqqатларидан",
    titleRu: "От трудностей пути",
    titleEn: "From hardships of travel",
    arabic: "اللَّهُمَّ إِنَّا نَعُوذُ بِكَ مِنْ وَعْثَاءِ السَّفَرِ وَكَآبَةِ الْمُنْقَلَبِ",
    uzbek: "Аллоҳим! Сафарнинг машаqqатидан ва қайтишнинг ғамгинлигидан Сенинг паноҳингни оламиз.",
    transliteration: "Allaahummaa innaa na'uuzu bika min wa'saais-safari wa kaabatil-munqalab",
  },
  {
    id: "s8",
    category: "safar",
    title: "Safar xayrli bo'lishi uchun",
    titleUz: "Сафар хайрли бўлиши учун",
    titleRu: "Для благополучия путешествия",
    titleEn: "For a blessed journey",
    arabic: "اللَّهُمَّ اجْعَلْ لَنَا فِي سَفَرِنَا هَذَا خَيْرًا",
    uzbek: "Аллоҳим! Бу сафаримизни хайрли қилгин.",
    transliteration: "Allaahummaj'al lanaa fii safarinaa haazaa khayran",
  },
];
