kind = "mobile"
previewPath = "/"
title = "Quran Uzbek"
version = "1.0.0"
id = "artifacts/quran-uzbek"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 18793

[services.development]
run = "pnpm --filter @workspace/quran-uzbek run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/quran-uzbek", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/quran-uzbek", "run", "serve" ]

[services.env]
PORT = "18793"
BASE_PATH = "/"
